[package]
name = "egui_winit_vulkano"
version = "0.19.0"
authors = ["hakolao <okkohakola@gmail.com>"]
edition = "2018"
description = "Egui immediate mode gui integration with winit and Vulkano"
homepage = "https://github.com/hakolao/egui_winit_vulkano"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/hakolao/egui_winit_vulkano"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]

[dependencies]
ahash = "0.7.6"
bytemuck = "1.8.0"
egui = "0.18.1"
image = "0.23.14"
vulkano = { version = "0.30.0", path = "../vulkano/vulkano" }
vulkano-shaders = "0.30.0"
winit = "0.26"

[target.'cfg(not(target_os = "ios"))'.dependencies]
egui-winit = "0.18.0"

[target.'cfg(target_os = "ios")'.dependencies]
egui-winit = { version = "0.18.0", default-features = false, features = [] }

[dev-dependencies]
cgmath = "0.18.0"
egui_demo_lib = "0.18.0"
vulkano-util = "0.30.0"
